name: covidapp
description: Application for covid 19, sofka style

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  stacked: ^1.1.0
  equatable: ^0.2.6
  flutter_bloc: ^4.0.0
  rxdart: ^0.24.1
  meta: ">=1.1.0 <2.0.0"
  http: ^0.12.0+1
  flutter_localizations:
    sdk: flutter
  flutter_simple_dependency_injection: any
  meet_network_image: ^0.1.2
  cupertino_icons: ^0.1.3
  dio: ^3.0.9
  flag: ^3.0.1
  tuple: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - ./assets/img/